// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwskhxqskdraqhruvme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d3NraHhxc2tkcmFxaHJ1dm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDE3OTYsImV4cCI6MjA4ODcxNzc5Nn0.lcktar2dXaLgNWAOw4EOTWY7IsFWZFkD8UP24ArqXPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});