// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qguyglzkedjslveifbes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFndXlnbHprZWRqc2x2ZWlmYmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDM3MzcsImV4cCI6MjA4ODcxOTczN30.IwDmWwQdajbuszq7cWRz7ByhMQ_snE2-xAfOWXlLm9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});